### ISSUE TITLE
New configuration documentation

### ISSUE THREAD

**Issue by parejkoj** [SublimeLinter/SublimeLinter-flake8#96]
First off, thank you for providing this package: it's a lifesaver for python development.

I've had a lot of trouble porting my settings after the SublimeLinter4 upgrade, as did several of my colleagues.  After reading #84 I was able to figure it out, but it would be great if you could put an example configuration in the Readme, and possibly a note about the change in how the settings are handled now.

#85 had a partial example, but it didn't include the new `--ignore` syntax, and it looks like that example wasn't merged.

Something like this in the readme would be very helpful (plus whatever other options you suggest), with a note about the change from SL3->SL4:

```
// SublimeLinter Settings - User
{
    "linters": {
        "flake8": {
            "args": [
                "--max-line-length", "110",
                "--ignore", "E133,E226",
            ],
        },
    },
}
```

It would also be helpful if the console showed an error when the old style of config was encountered (e.g. with `ignore: ["N123", "E123", "D123],`), though I suspect that's up to the SublimeLinter package itself?

**Comment by braver** [comment]
While we communicated a lot about the changes in SL4, what you’re dealing with are the (related) changes in flake8 specifically. And communication there could definitely have been better.

Essentially, this plugin no longer has settings of its own. Previously it provided aliases for command line arguments, now you simply set the args directly. All generic settings that are available to any linter plugin are documented here: http://www.sublimelinter.com/en/stable/linter_settings.html

It’s been almost 3 months since 4.0 landed, so we’re not going to add new documentation about the transition. But if you have questions, don’t be afraid to ask.

We have some validation for settings, but nothing specific for the old settings because that would take more time.

**Comment by kaste** [comment]
I think a bit more README wouldn't be strictly overkill here. PR's welcome.

@parejkoj 

```
            "args": [
                "--max-line-length", "110",
                "--ignore", "E133,E226",
            ],
```

From a user perspective (UX, ergonomics), such simple `args` can be given as a string. (So you basically copy/paste from your shell. E.g.

```
	"args": "--max-line-length 110 --ignore E133,E226"
```

Giving that example, I think we can say we progressed bc you don't have to learn a new way to configure flake8 to work with SublimeLinter, instead you just copy/paste from the cli command you know how to write.

**Comment by braver** [comment]
> I think we can say we progressed bc you don't have to learn a new way to configure flake8 to work with SublimeLinter, instead you just copy/paste from the cli command you know how to write.

Exactly.

PR’s for howto’s and tutorials are totally welcome by the way!

**Comment by parejkoj** [comment]
> Giving that example, I think we can say we progressed bc you don't have to learn a new way to configure flake8 to work with SublimeLinter, instead you just copy/paste from the cli command you know how to write.

I never used flake8 from the commandline with arguments, so I didn't know about those arguments. I always and only ran it from within SublimeText via SL3, or indirectly as part of our pytest suite that was configured by `setup.cfg`.

Should I make a PR with an update to the Readme?
